# Generated by Django 4.0.6 on 2022-07-12 05:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('product_category', models.CharField(choices=[('Jeans', 'Jeans'), ('Tshirt', 'Tshirt'), ('Shoes', 'Shoes'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket')], max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/')),
            ],
        ),
    ]
